### PR TITLE
Trying Router.route

### PR DESCRIPTION
**Pull request by Allizine**
Trying something :)

### CODE REVIEW

**Review by IThinkThatsKirby — COMMENTED** [review]
This looks super spooky. To many nests.

**Comment by Allizine** [comment]
> This looks super spooky. To many nests.

Understandable- just condenses the code a bit.

**Review by RyanJRasmussen — CHANGES_REQUESTED** [review]
Change post request to get request in the bottom, promise section, and add comments explaining the unique code

**Review by IThinkThatsKirby — APPROVED** [review]

**Review by RyanJRasmussen — APPROVED** [review]
Probably going to change this format since we have to re do our routes to include linking tables

**Pull request closed without merging**
